-- Pool curado de passagens por família emocional (~12 por família).
-- Apenas REFERÊNCIAS: o texto vem de bible_verses (Bíblia Livre) na geração.
-- Toda referência é validada contra o banco por scripts/import-bible.ts.

INSERT INTO passage_pool (family, book, chapter, verse_start, verse_end, reference, note) VALUES
-- ANSIEDADE ------------------------------------------------------------------
('ansiedade','Filipenses',4,6,7,'Filipenses 4:6-7','entrega da ansiedade em oração; a paz que guarda'),
('ansiedade','1 Pedro',5,7,NULL,'1 Pedro 5:7','lançar sobre Ele toda ansiedade'),
('ansiedade','Mateus',6,25,27,'Mateus 6:25-27','não andeis ansiosos pela vida'),
('ansiedade','Mateus',6,34,NULL,'Mateus 6:34','basta a cada dia o seu mal'),
('ansiedade','Salmos',55,22,NULL,'Salmos 55:22','lança o teu cuidado sobre o SENHOR'),
('ansiedade','Isaías',41,10,NULL,'Isaías 41:10','não temas, eu estou contigo'),
('ansiedade','Salmos',94,19,NULL,'Salmos 94:19','consolações no meio das inquietações'),
('ansiedade','João',14,27,NULL,'João 14:27','a paz que o mundo não dá'),
('ansiedade','Mateus',11,28,30,'Mateus 11:28-30','vinde a mim os cansados'),
('ansiedade','Salmos',121,1,2,'Salmos 121:1-2','o socorro vem do SENHOR'),
('ansiedade','Provérbios',3,5,6,'Provérbios 3:5-6','confia de todo o coração'),
('ansiedade','Salmos',46,1,2,'Salmos 46:1-2','refúgio e socorro presente'),
-- PAZ ------------------------------------------------------------------------
('paz','João',14,27,NULL,'João 14:27','a minha paz vos dou'),
('paz','Filipenses',4,7,NULL,'Filipenses 4:7','a paz que excede todo entendimento'),
('paz','Salmos',4,8,NULL,'Salmos 4:8','deitar e dormir em paz'),
('paz','Isaías',26,3,NULL,'Isaías 26:3','mente firme, perfeita paz'),
('paz','Salmos',23,1,3,'Salmos 23:1-3','águas tranquilas, alma restaurada'),
('paz','Colossenses',3,15,NULL,'Colossenses 3:15','a paz reine nos corações'),
('paz','Salmos',29,11,NULL,'Salmos 29:11','o SENHOR abençoa com paz'),
('paz','Isaías',32,17,NULL,'Isaías 32:17','o efeito da justiça será paz'),
('paz','João',16,33,NULL,'João 16:33','em mim tenhais paz'),
('paz','Números',6,24,26,'Números 6:24-26','a bênção do descanso no rosto de Deus'),
('paz','Salmos',37,7,NULL,'Salmos 37:7','descansa no SENHOR e espera'),
('paz','Mateus',11,28,NULL,'Mateus 11:28','eu vos farei descansar'),
-- ESPERANÇA ------------------------------------------------------------------
('esperança','Jeremias',29,11,NULL,'Jeremias 29:11','pensamentos de paz e um futuro'),
('esperança','Lamentações',3,22,23,'Lamentações 3:22-23','misericórdias novas a cada manhã'),
('esperança','Romanos',15,13,NULL,'Romanos 15:13','o Deus da esperança vos encha'),
('esperança','Salmos',42,5,NULL,'Salmos 42:5','espera em Deus, alma abatida'),
('esperança','Isaías',40,31,NULL,'Isaías 40:31','renovam as forças, sobem com asas'),
('esperança','Romanos',8,28,NULL,'Romanos 8:28','todas as coisas cooperam para o bem'),
('esperança','Salmos',30,5,NULL,'Salmos 30:5','o choro dura uma noite, a alegria vem pela manhã'),
('esperança','Habacuque',3,17,18,'Habacuque 3:17-18','ainda que a figueira não floresça'),
('esperança','Salmos',27,13,14,'Salmos 27:13-14','veria a bondade do SENHOR; espera'),
('esperança','2 Coríntios',4,16,18,'2 Coríntios 4:16-18','o que se renova dia após dia'),
('esperança','Romanos',5,3,5,'Romanos 5:3-5','a tribulação produz esperança'),
('esperança','Salmos',71,14,NULL,'Salmos 71:14','esperarei sempre, e te louvarei mais'),
-- PROPÓSITO ------------------------------------------------------------------
('propósito','Efésios',2,10,NULL,'Efésios 2:10','criados para as boas obras'),
('propósito','Jeremias',1,5,NULL,'Jeremias 1:5','antes de te formar eu te conheci'),
('propósito','Provérbios',16,9,NULL,'Provérbios 16:9','o coração planeja, o SENHOR dirige'),
('propósito','Salmos',138,8,NULL,'Salmos 138:8','o SENHOR aperfeiçoará o que me toca'),
('propósito','Romanos',12,2,NULL,'Romanos 12:2','provar a boa vontade de Deus'),
('propósito','Colossenses',3,23,NULL,'Colossenses 3:23','fazei de coração, como ao Senhor'),
('propósito','Provérbios',19,21,NULL,'Provérbios 19:21','o propósito do SENHOR permanece'),
('propósito','Filipenses',1,6,NULL,'Filipenses 1:6','quem começou a boa obra a completará'),
('propósito','1 Coríntios',15,58,NULL,'1 Coríntios 15:58','vosso trabalho não é vão no Senhor'),
('propósito','Miquéias',6,8,NULL,'Miqueias 6:8','o que o SENHOR pede de ti'),
('propósito','Salmos',32,8,NULL,'Salmos 32:8','te instruirei no caminho'),
('propósito','Ester',4,14,NULL,'Ester 4:14','para um tempo como este'),
-- GRATIDÃO -------------------------------------------------------------------
('gratidão','1 Tessalonicenses',5,18,NULL,'1 Tessalonicenses 5:18','em tudo dai graças'),
('gratidão','Salmos',103,1,2,'Salmos 103:1-2','não te esqueças de nenhum benefício'),
('gratidão','Salmos',100,4,5,'Salmos 100:4-5','entrai com ações de graças'),
('gratidão','Colossenses',3,17,NULL,'Colossenses 3:17','tudo em nome do Senhor, dando graças'),
('gratidão','Salmos',136,1,NULL,'Salmos 136:1','a sua misericórdia dura para sempre'),
('gratidão','Tiago',1,17,NULL,'Tiago 1:17','toda boa dádiva vem do alto'),
('gratidão','Filipenses',4,19,NULL,'Filipenses 4:19','meu Deus suprirá todas as necessidades'),
('gratidão','Salmos',118,1,NULL,'Salmos 118:1','dai graças porque ele é bom'),
('gratidão','Efésios',5,20,NULL,'Efésios 5:20','dando graças sempre por tudo'),
('gratidão','Salmos',9,1,NULL,'Salmos 9:1','contarei todas as tuas maravilhas'),
('gratidão','2 Coríntios',9,15,NULL,'2 Coríntios 9:15','graças pelo dom inefável'),
('gratidão','Salmos',107,1,NULL,'Salmos 107:1','celebrai a bondade do SENHOR'),
-- FÉ -------------------------------------------------------------------------
('fé','Hebreus',11,1,NULL,'Hebreus 11:1','a certeza do que se espera'),
('fé','Marcos',9,23,24,'Marcos 9:23-24','creio; ajuda a minha incredulidade'),
('fé','2 Coríntios',5,7,NULL,'2 Coríntios 5:7','andamos por fé, não por vista'),
('fé','Romanos',10,17,NULL,'Romanos 10:17','a fé vem pelo ouvir'),
('fé','Mateus',17,20,NULL,'Mateus 17:20','fé como grão de mostarda'),
('fé','Hebreus',11,6,NULL,'Hebreus 11:6','sem fé é impossível agradá-lo'),
('fé','Tiago',1,6,NULL,'Tiago 1:6','peça com fé, sem duvidar'),
('fé','Marcos',11,22,24,'Marcos 11:22-24','tende fé em Deus'),
('fé','Provérbios',3,5,6,'Provérbios 3:5-6','não te estribes no teu entendimento'),
('fé','Salmos',37,5,NULL,'Salmos 37:5','entrega o teu caminho ao SENHOR'),
('fé','Gálatas',2,20,NULL,'Gálatas 2:20','vivo pela fé no Filho de Deus'),
('fé','1 Pedro',1,8,9,'1 Pedro 1:8-9','sem ver, crendo, vos alegrais'),
-- SOLIDÃO --------------------------------------------------------------------
('solidão','Salmos',23,4,NULL,'Salmos 23:4','tu estás comigo no vale'),
('solidão','Isaías',41,10,NULL,'Isaías 41:10','eu estou contigo, não temas'),
('solidão','Deuteronômio',31,6,NULL,'Deuteronômio 31:6','não te deixará nem te desamparará'),
('solidão','Mateus',28,20,NULL,'Mateus 28:20','estou convosco todos os dias'),
('solidão','Salmos',27,10,NULL,'Salmos 27:10','ainda que pai e mãe me deixem'),
('solidão','Salmos',68,5,6,'Salmos 68:5-6','Deus faz habitar em família os solitários'),
('solidão','Josué',1,9,NULL,'Josué 1:9','o SENHOR vai contigo por onde andares'),
('solidão','Salmos',139,7,10,'Salmos 139:7-10','para onde fugirei da tua presença?'),
('solidão','Isaías',43,2,NULL,'Isaías 43:2','nas águas e no fogo, eu estarei contigo'),
('solidão','Romanos',8,38,39,'Romanos 8:38-39','nada nos separa do amor de Deus'),
('solidão','Hebreus',13,5,NULL,'Hebreus 13:5','não te deixarei, não te desampararei'),
('solidão','Salmos',25,16,NULL,'Salmos 25:16','olha para mim, estou solitário e aflito'),
-- LUTO -----------------------------------------------------------------------
('luto','Mateus',5,4,NULL,'Mateus 5:4','bem-aventurados os que choram'),
('luto','Salmos',34,18,NULL,'Salmos 34:18','perto está dos quebrantados de coração'),
('luto','Apocalipse',21,4,NULL,'Apocalipse 21:4','enxugará toda lágrima'),
('luto','Salmos',147,3,NULL,'Salmos 147:3','sara os quebrantados e ata as feridas'),
('luto','João',11,25,26,'João 11:25-26','eu sou a ressurreição e a vida'),
('luto','2 Coríntios',1,3,4,'2 Coríntios 1:3-4','o Deus de toda consolação'),
('luto','Salmos',30,11,NULL,'Salmos 30:11','tornaste o meu pranto em dança'),
('luto','Isaías',61,3,NULL,'Isaías 61:3','coroa em vez de cinzas'),
('luto','1 Tessalonicenses',4,13,14,'1 Tessalonicenses 4:13-14','não como os que não têm esperança'),
('luto','João',14,1,3,'João 14:1-3','não se turbe o vosso coração'),
('luto','Salmos',116,15,NULL,'Salmos 116:15','preciosa é a morte dos seus santos'),
('luto','Eclesiastes',3,1,4,'Eclesiastes 3:1-4','tempo de chorar e tempo de rir'),
-- CULPA ----------------------------------------------------------------------
('culpa','1 João',1,9,NULL,'1 João 1:9','fiel e justo para perdoar'),
('culpa','Salmos',103,12,NULL,'Salmos 103:12','afasta as transgressões como o oriente do ocidente'),
('culpa','Romanos',8,1,NULL,'Romanos 8:1','nenhuma condenação para os que estão em Cristo'),
('culpa','Isaías',1,18,NULL,'Isaías 1:18','ainda que escarlates, brancos como a neve'),
('culpa','Miquéias',7,18,19,'Miqueias 7:18-19','lança os pecados nas profundezas do mar'),
('culpa','Salmos',51,10,NULL,'Salmos 51:10','cria em mim um coração puro'),
('culpa','Efésios',1,7,NULL,'Efésios 1:7','redenção e perdão pelo seu sangue'),
('culpa','2 Coríntios',5,17,NULL,'2 Coríntios 5:17','nova criatura; as coisas velhas passaram'),
('culpa','Salmos',32,5,NULL,'Salmos 32:5','confessei, e perdoaste'),
('culpa','Isaías',43,25,NULL,'Isaías 43:25','não me lembro dos teus pecados'),
('culpa','Lucas',15,20,NULL,'Lucas 15:20','o pai correu e o abraçou'),
('culpa','Hebreus',8,12,NULL,'Hebreus 8:12','das suas iniquidades não me lembrarei'),
-- ALEGRIA --------------------------------------------------------------------
('alegria','Salmos',118,24,NULL,'Salmos 118:24','este é o dia que o SENHOR fez'),
('alegria','Neemias',8,10,NULL,'Neemias 8:10','a alegria do SENHOR é a vossa força'),
('alegria','Filipenses',4,4,NULL,'Filipenses 4:4','alegrai-vos sempre no Senhor'),
('alegria','Salmos',16,11,NULL,'Salmos 16:11','plenitude de alegria na tua presença'),
('alegria','João',15,11,NULL,'João 15:11','a minha alegria em vós, alegria completa'),
('alegria','Salmos',126,2,3,'Salmos 126:2-3','a boca cheia de riso'),
('alegria','Romanos',15,13,NULL,'Romanos 15:13','todo gozo e paz no crer'),
('alegria','Salmos',100,1,2,'Salmos 100:1-2','servi ao SENHOR com alegria'),
('alegria','Provérbios',17,22,NULL,'Provérbios 17:22','o coração alegre é bom remédio'),
('alegria','1 Pedro',1,8,NULL,'1 Pedro 1:8','alegria indizível e gloriosa'),
('alegria','Salmos',98,4,NULL,'Salmos 98:4','celebrai com júbilo ao SENHOR'),
('alegria','Isaías',55,12,NULL,'Isaías 55:12','saireis com alegria, em paz sereis guiados')
ON CONFLICT (family, reference) DO NOTHING;
