-- Expansão do pool de passagens: lote 2 (+26 por família = +260).
-- Meta: sustentar 365+ sementes sem repetir referência dentro da família.
-- Apenas REFERÊNCIAS: o texto vem de bible_verses (Bíblia Livre).
-- Validar com: npm run content:validate-pool

INSERT INTO passage_pool (family, book, chapter, verse_start, verse_end, reference, note) VALUES
-- ANSIEDADE ------------------------------------------------------------------
('ansiedade','Salmos',34,4,NULL,'Salmos 34:4','busquei ao SENHOR e ele me livrou de todos os temores'),
('ansiedade','Salmos',56,3,NULL,'Salmos 56:3','no dia em que eu temer, confiarei em ti'),
('ansiedade','Salmos',62,1,2,'Salmos 62:1-2','somente em Deus a alma descansa'),
('ansiedade','Salmos',91,1,2,'Salmos 91:1-2','o abrigo do Altíssimo'),
('ansiedade','Salmos',112,7,NULL,'Salmos 112:7','não teme más notícias; coração firme'),
('ansiedade','Salmos',131,1,2,'Salmos 131:1-2','alma quieta como criança no colo'),
('ansiedade','Isaías',35,4,NULL,'Isaías 35:4','dizei aos turbados de coração: sede fortes'),
('ansiedade','Isaías',40,29,NULL,'Isaías 40:29','dá força ao cansado'),
('ansiedade','Jeremias',17,7,8,'Jeremias 17:7-8','árvore plantada junto às águas, sem medo do calor'),
('ansiedade','Lamentações',3,25,26,'Lamentações 3:25-26','bom é esperar em silêncio a salvação'),
('ansiedade','Naum',1,7,NULL,'Naum 1:7','fortaleza no dia da angústia'),
('ansiedade','Isaías',51,12,NULL,'Isaías 51:12','eu sou aquele que vos consola'),
('ansiedade','Mateus',8,26,NULL,'Mateus 8:26','Jesus acalma a tempestade: por que temeis?'),
('ansiedade','Marcos',4,39,40,'Marcos 4:39-40','cala-te, aquieta-te'),
('ansiedade','Lucas',12,25,26,'Lucas 12:25-26','a ansiedade não acrescenta um côvado à vida'),
('ansiedade','João',6,20,NULL,'João 6:20','sou eu, não temais'),
('ansiedade','Romanos',8,31,NULL,'Romanos 8:31','se Deus é por nós, quem será contra nós'),
('ansiedade','Filipenses',4,8,NULL,'Filipenses 4:8','redirecionar o pensamento para o que é bom'),
('ansiedade','2 Timóteo',1,7,NULL,'2 Timóteo 1:7','não nos deu espírito de temor'),
('ansiedade','Hebreus',13,6,NULL,'Hebreus 13:6','o Senhor é meu ajudador, não temerei'),
('ansiedade','Salmos',3,5,NULL,'Salmos 3:5','deito-me e durmo, pois o SENHOR me sustenta'),
('ansiedade','Salmos',27,1,NULL,'Salmos 27:1','o SENHOR é minha luz; a quem temerei'),
('ansiedade','Salmos',61,2,NULL,'Salmos 61:2','leva-me à rocha mais alta do que eu'),
('ansiedade','Salmos',86,7,NULL,'Salmos 86:7','no dia da angústia clamo a ti, porque respondes'),
('ansiedade','Salmos',118,5,6,'Salmos 118:5-6','da angústia clamei; o SENHOR está comigo'),
('ansiedade','Isaías',43,1,NULL,'Isaías 43:1','não temas: eu te chamei pelo teu nome'),
-- PAZ ------------------------------------------------------------------------
('paz','Salmos',34,14,NULL,'Salmos 34:14','busca a paz e segue-a'),
('paz','Salmos',46,10,NULL,'Salmos 46:10','aquietai-vos e sabei que eu sou Deus'),
('paz','Salmos',85,8,NULL,'Salmos 85:8','Deus falará de paz ao seu povo'),
('paz','Salmos',119,165,NULL,'Salmos 119:165','muita paz têm os que amam a tua lei'),
('paz','Salmos',37,11,NULL,'Salmos 37:11','os mansos terão abundância de paz'),
('paz','Provérbios',14,30,NULL,'Provérbios 14:30','coração tranquilo é vida para o corpo'),
('paz','Eclesiastes',4,6,NULL,'Eclesiastes 4:6','melhor um punhado com tranquilidade'),
('paz','Isaías',30,15,NULL,'Isaías 30:15','em quietude e confiança está a vossa força'),
('paz','Isaías',54,10,NULL,'Isaías 54:10','os montes se desviarão, mas minha paz não'),
('paz','Romanos',15,33,NULL,'Romanos 15:33','o Deus de paz seja com todos'),
('paz','Jeremias',6,16,NULL,'Jeremias 6:16','parai nos caminhos e achareis descanso'),
('paz','Lucas',24,36,NULL,'Lucas 24:36','o ressuscitado chega dizendo: paz seja convosco'),
('paz','Romanos',5,1,NULL,'Romanos 5:1','justificados pela fé, temos paz com Deus'),
('paz','Romanos',8,6,NULL,'Romanos 8:6','a inclinação do Espírito é vida e paz'),
('paz','Romanos',12,18,NULL,'Romanos 12:18','no que depender de vós, tende paz com todos'),
('paz','Romanos',14,17,NULL,'Romanos 14:17','o reino é justiça, paz e alegria'),
('paz','1 Coríntios',14,33,NULL,'1 Coríntios 14:33','Deus não é de confusão, mas de paz'),
('paz','Gálatas',5,22,23,'Gálatas 5:22-23','o fruto do Espírito'),
('paz','Efésios',2,14,NULL,'Efésios 2:14','ele é a nossa paz'),
('paz','Colossenses',1,20,NULL,'Colossenses 1:20','paz pelo sangue da cruz'),
('paz','2 Tessalonicenses',3,16,NULL,'2 Tessalonicenses 3:16','o Senhor da paz vos dê paz em todo tempo'),
('paz','Tiago',3,18,NULL,'Tiago 3:18','o fruto da justiça semeia-se na paz'),
('paz','Isaías',66,12,NULL,'Isaías 66:12','estenderei sobre ela a paz como um rio'),
('paz','Salmos',116,7,NULL,'Salmos 116:7','volta, alma minha, ao teu repouso'),
('paz','Salmos',127,2,NULL,'Salmos 127:2','aos seus amados ele dá o sono'),
('paz','Mateus',5,9,NULL,'Mateus 5:9','bem-aventurados os pacificadores'),
-- ESPERANÇA ------------------------------------------------------------------
('esperança','Salmos',33,18,NULL,'Salmos 33:18','os olhos do SENHOR sobre os que esperam'),
('esperança','Salmos',39,7,NULL,'Salmos 39:7','minha esperança está em ti'),
('esperança','Salmos',62,5,6,'Salmos 62:5-6','espera somente em Deus, ó minha alma'),
('esperança','Salmos',130,5,6,'Salmos 130:5-6','espero mais que os guardas pela manhã'),
('esperança','Salmos',146,5,NULL,'Salmos 146:5','feliz aquele cuja esperança está no SENHOR'),
('esperança','Provérbios',23,18,NULL,'Provérbios 23:18','há um futuro; tua esperança não será cortada'),
('esperança','Isaías',43,18,19,'Isaías 43:18-19','eis que faço uma coisa nova'),
('esperança','Jeremias',31,17,NULL,'Jeremias 31:17','há esperança para o teu futuro'),
('esperança','Jeremias',32,27,NULL,'Jeremias 32:27','haveria algo difícil demais para mim?'),
('esperança','Joel',2,25,NULL,'Joel 2:25','restituirei os anos que o gafanhoto comeu'),
('esperança','Miquéias',7,7,NULL,'Miquéias 7:7','esperarei no Deus da minha salvação'),
('esperança','Zacarias',9,12,NULL,'Zacarias 9:12','presos de esperança'),
('esperança','Mateus',12,20,NULL,'Mateus 12:20','não quebrará a cana rachada'),
('esperança','Lucas',1,37,NULL,'Lucas 1:37','para Deus nada é impossível'),
('esperança','João',11,40,NULL,'João 11:40','se creres, verás a glória de Deus'),
('esperança','Romanos',4,18,NULL,'Romanos 4:18','contra a esperança, creu em esperança'),
('esperança','Romanos',8,24,25,'Romanos 8:24-25','esperar com paciência o que não se vê'),
('esperança','Romanos',12,12,NULL,'Romanos 12:12','alegrai-vos na esperança'),
('esperança','1 Coríntios',2,9,NULL,'1 Coríntios 2:9','o que o olho não viu, Deus preparou'),
('esperança','Gálatas',6,9,NULL,'Gálatas 6:9','não nos cansemos: a seu tempo ceifaremos'),
('esperança','Efésios',3,20,NULL,'Efésios 3:20','capaz de fazer muito mais do que pedimos'),
('esperança','Hebreus',6,19,NULL,'Hebreus 6:19','a esperança como âncora da alma'),
('esperança','Hebreus',10,23,NULL,'Hebreus 10:23','fiel é aquele que prometeu'),
('esperança','1 Pedro',1,3,NULL,'1 Pedro 1:3','esperança viva pela ressurreição'),
('esperança','Apocalipse',21,5,NULL,'Apocalipse 21:5','faço novas todas as coisas'),
('esperança','Salmos',126,5,6,'Salmos 126:5-6','quem semeia em lágrimas ceifará com júbilo'),
-- PROPÓSITO ------------------------------------------------------------------
('propósito','Gênesis',1,27,NULL,'Gênesis 1:27','criado à imagem de Deus'),
('propósito','Deuteronômio',30,19,NULL,'Deuteronômio 30:19','escolhe a vida'),
('propósito','Josué',1,8,NULL,'Josué 1:8','a palavra como bússola do caminho'),
('propósito','1 Samuel',16,7,NULL,'1 Samuel 16:7','o SENHOR olha o coração'),
('propósito','Salmos',25,4,5,'Salmos 25:4-5','mostra-me os teus caminhos'),
('propósito','Salmos',37,23,NULL,'Salmos 37:23','os passos confirmados pelo SENHOR'),
('propósito','Salmos',57,2,NULL,'Salmos 57:2','o Deus que cumpre seu propósito para comigo'),
('propósito','Salmos',90,12,NULL,'Salmos 90:12','ensina-nos a contar os nossos dias'),
('propósito','Salmos',90,17,NULL,'Salmos 90:17','confirma a obra das nossas mãos'),
('propósito','Salmos',119,105,NULL,'Salmos 119:105','lâmpada para os meus pés'),
('propósito','Provérbios',4,25,27,'Provérbios 4:25-27','olhos adiante, pondera a vereda'),
('propósito','Eclesiastes',3,11,NULL,'Eclesiastes 3:11','tudo fez formoso no seu tempo'),
('propósito','Eclesiastes',9,10,NULL,'Eclesiastes 9:10','o que vier à mão, faze com toda a força'),
('propósito','Isaías',6,8,NULL,'Isaías 6:8','eis-me aqui, envia-me'),
('propósito','Isaías',30,21,NULL,'Isaías 30:21','este é o caminho, andai nele'),
('propósito','Isaías',58,10,NULL,'Isaías 58:10','derramar-se pelo faminto; a luz nasce na entrega'),
('propósito','Jeremias',29,13,NULL,'Jeremias 29:13','buscar-me-eis e me achareis'),
('propósito','Mateus',5,14,16,'Mateus 5:14-16','vós sois a luz do mundo'),
('propósito','Mateus',6,33,NULL,'Mateus 6:33','buscai primeiro o Reino'),
('propósito','Mateus',25,21,NULL,'Mateus 25:21','fiel no pouco'),
('propósito','João',12,26,NULL,'João 12:26','quem me serve, siga-me'),
('propósito','João',15,16,NULL,'João 15:16','eu vos designei para que deis fruto'),
('propósito','Atos',20,35,NULL,'Atos 20:35','mais bem-aventurado é dar'),
('propósito','1 Coríntios',10,31,NULL,'1 Coríntios 10:31','fazei tudo para a glória de Deus'),
('propósito','2 Timóteo',1,9,NULL,'2 Timóteo 1:9','chamados segundo o seu propósito e graça'),
('propósito','1 Pedro',4,10,NULL,'1 Pedro 4:10','cada um administre o dom que recebeu'),
-- GRATIDÃO -------------------------------------------------------------------
('gratidão','Deuteronômio',8,10,NULL,'Deuteronômio 8:10','comerás, te fartarás e bendirás'),
('gratidão','1 Crônicas',16,34,NULL,'1 Crônicas 16:34','sua bondade dura para sempre'),
('gratidão','1 Crônicas',29,14,NULL,'1 Crônicas 29:14','tudo vem de ti; do que é teu te damos'),
('gratidão','Salmos',13,6,NULL,'Salmos 13:6','cantarei, porque me fez bem'),
('gratidão','Salmos',28,7,NULL,'Salmos 28:7','meu coração exulta e com meu cântico o louvarei'),
('gratidão','Salmos',30,12,NULL,'Salmos 30:12','para que eu te cante e não me cale'),
('gratidão','Salmos',34,1,NULL,'Salmos 34:1','louvarei ao SENHOR em todo tempo'),
('gratidão','Salmos',65,11,NULL,'Salmos 65:11','coroas o ano da tua bondade'),
('gratidão','Salmos',92,1,2,'Salmos 92:1-2','bom é render graças de manhã e de noite'),
('gratidão','Salmos',95,2,NULL,'Salmos 95:2','chegar diante dele com ações de graças'),
('gratidão','Salmos',116,12,NULL,'Salmos 116:12','que darei ao SENHOR por seus benefícios?'),
('gratidão','Salmos',111,1,NULL,'Salmos 111:1','louvarei de todo o coração'),
('gratidão','Salmos',138,1,NULL,'Salmos 138:1','louvor de coração inteiro'),
('gratidão','Salmos',147,7,NULL,'Salmos 147:7','cantai com ação de graças'),
('gratidão','Isaías',12,4,NULL,'Isaías 12:4','dai graças e invocai o seu nome'),
('gratidão','Jonas',2,9,NULL,'Jonas 2:9','com voz de agradecimento sacrificarei'),
('gratidão','Lucas',17,15,16,'Lucas 17:15-16','o samaritano que voltou para agradecer'),
('gratidão','João',6,11,NULL,'João 6:11','Jesus deu graças e repartiu'),
('gratidão','Atos',16,25,NULL,'Atos 16:25','cantando hinos na prisão'),
('gratidão','2 Coríntios',4,15,NULL,'2 Coríntios 4:15','a graça faz abundar a ação de graças'),
('gratidão','Filipenses',1,3,NULL,'Filipenses 1:3','dou graças toda vez que me lembro de vós'),
('gratidão','Colossenses',2,6,7,'Colossenses 2:6-7','arraigados nele, abundando em gratidão'),
('gratidão','Colossenses',4,2,NULL,'Colossenses 4:2','perseverai na oração com ação de graças'),
('gratidão','1 Timóteo',4,4,5,'1 Timóteo 4:4-5','tudo é bom quando recebido com gratidão'),
('gratidão','Hebreus',12,28,NULL,'Hebreus 12:28','um reino inabalável: tenhamos gratidão'),
('gratidão','Hebreus',13,15,NULL,'Hebreus 13:15','sacrifício de louvor, fruto dos lábios'),
-- FÉ -------------------------------------------------------------------------
('fé','Gênesis',15,6,NULL,'Gênesis 15:6','creu no SENHOR, e lhe foi contado como justiça'),
('fé','Êxodo',14,14,NULL,'Êxodo 14:14','o SENHOR lutará por vós'),
('fé','2 Crônicas',20,12,NULL,'2 Crônicas 20:12','não sabemos o que fazer, mas os olhos estão em ti'),
('fé','Jó',19,25,NULL,'Jó 19:25','eu sei que o meu Redentor vive'),
('fé','Jó',23,10,NULL,'Jó 23:10','provando-me, sairei como o ouro'),
('fé','Salmos',18,2,NULL,'Salmos 18:2','o SENHOR é minha rocha'),
('fé','Salmos',20,7,NULL,'Salmos 20:7','uns confiam em carros; nós, no nome do SENHOR'),
('fé','Salmos',31,14,15,'Salmos 31:14-15','nas tuas mãos estão os meus tempos'),
('fé','Salmos',84,12,NULL,'Salmos 84:12','bem-aventurado o homem que em ti confia'),
('fé','Salmos',125,1,NULL,'Salmos 125:1','como o monte Sião, que não se abala'),
('fé','Isaías',50,10,NULL,'Isaías 50:10','quem anda em trevas, confie no nome do SENHOR'),
('fé','Daniel',3,17,18,'Daniel 3:17-18','nosso Deus pode livrar; mas, se não…'),
('fé','Mateus',8,8,NULL,'Mateus 8:8','dize uma palavra, e será curado'),
('fé','Mateus',9,20,22,'Mateus 9:20-22','a que tocou a borda do manto'),
('fé','Mateus',14,29,31,'Mateus 14:29-31','Pedro sobre as águas; a mão que segura'),
('fé','Marcos',5,36,NULL,'Marcos 5:36','não temas, crê somente'),
('fé','Marcos',10,52,NULL,'Marcos 10:52','a fé de Bartimeu'),
('fé','Lucas',7,50,NULL,'Lucas 7:50','a tua fé te salvou; vai em paz'),
('fé','João',20,29,NULL,'João 20:29','bem-aventurados os que não viram e creram'),
('fé','Romanos',1,17,NULL,'Romanos 1:17','o justo viverá da fé'),
('fé','Romanos',4,20,21,'Romanos 4:20-21','plenamente convicto de que Deus é poderoso'),
('fé','2 Coríntios',1,20,NULL,'2 Coríntios 1:20','as promessas de Deus são sim nele'),
('fé','Efésios',2,8,9,'Efésios 2:8-9','pela graça, por meio da fé'),
('fé','Efésios',6,16,NULL,'Efésios 6:16','o escudo da fé'),
('fé','Hebreus',12,1,2,'Hebreus 12:1-2','olhando para Jesus, autor e consumador'),
('fé','1 João',5,4,NULL,'1 João 5:4','esta é a vitória: a nossa fé'),
-- ALEGRIA --------------------------------------------------------------------
('alegria','Deuteronômio',16,11,NULL,'Deuteronômio 16:11','alegrar-se diante do SENHOR com os seus'),
('alegria','1 Samuel',2,1,NULL,'1 Samuel 2:1','o coração de Ana exulta no SENHOR'),
('alegria','1 Crônicas',16,31,NULL,'1 Crônicas 16:31','alegrem-se os céus e a terra'),
('alegria','Salmos',5,11,NULL,'Salmos 5:11','alegrem-se todos os que confiam em ti'),
('alegria','Salmos',9,2,NULL,'Salmos 9:2','em ti me alegrarei e saltarei de prazer'),
('alegria','Salmos',19,8,NULL,'Salmos 19:8','os preceitos do SENHOR alegram o coração'),
('alegria','Salmos',32,11,NULL,'Salmos 32:11','alegrai-vos no SENHOR'),
('alegria','Salmos',33,21,NULL,'Salmos 33:21','nele se alegra o nosso coração'),
('alegria','Salmos',47,1,NULL,'Salmos 47:1','batei palmas, todos os povos'),
('alegria','Salmos',65,8,NULL,'Salmos 65:8','as saídas da manhã e da tarde cantam de alegria'),
('alegria','Salmos',68,3,NULL,'Salmos 68:3','os justos saltem de prazer diante de Deus'),
('alegria','Salmos',90,14,NULL,'Salmos 90:14','farta-nos de manhã e cantaremos alegres'),
('alegria','Salmos',92,4,NULL,'Salmos 92:4','tu me alegraste com os teus feitos'),
('alegria','Salmos',97,11,12,'Salmos 97:11-12','semeia-se a luz e a alegria para o justo'),
('alegria','Salmos',104,33,34,'Salmos 104:33-34','cantarei enquanto eu viver'),
('alegria','Provérbios',15,13,NULL,'Provérbios 15:13','o coração alegre aformoseia o rosto'),
('alegria','Provérbios',15,15,NULL,'Provérbios 15:15','coração contente tem banquete contínuo'),
('alegria','Eclesiastes',3,12,13,'Eclesiastes 3:12-13','alegrar-se e fazer o bem é dom de Deus'),
('alegria','Isaías',12,3,NULL,'Isaías 12:3','tirar água com alegria das fontes da salvação'),
('alegria','Isaías',61,10,NULL,'Isaías 61:10','grandemente me alegro no SENHOR'),
('alegria','Sofonias',3,17,NULL,'Sofonias 3:17','ele se alegrará em ti com júbilo'),
('alegria','Lucas',2,10,NULL,'Lucas 2:10','novas de grande alegria'),
('alegria','Lucas',10,20,NULL,'Lucas 10:20','alegrai-vos: vossos nomes estão nos céus'),
('alegria','João',16,22,NULL,'João 16:22','vossa alegria ninguém tirará'),
('alegria','Atos',13,52,NULL,'Atos 13:52','cheios de alegria e do Espírito Santo'),
('alegria','1 Tessalonicenses',5,16,NULL,'1 Tessalonicenses 5:16','alegrai-vos sempre'),
-- SOLIDÃO --------------------------------------------------------------------
('solidão','Gênesis',28,15,NULL,'Gênesis 28:15','estou contigo e te guardarei por onde fores'),
('solidão','Êxodo',33,14,NULL,'Êxodo 33:14','minha presença irá contigo'),
('solidão','Deuteronômio',31,8,NULL,'Deuteronômio 31:8','o SENHOR vai adiante de ti'),
('solidão','1 Reis',19,11,12,'1 Reis 19:11-12','a voz mansa e delicada na caverna de Elias'),
('solidão','Salmos',9,10,NULL,'Salmos 9:10','não desamparas os que te buscam'),
('solidão','Salmos',16,8,NULL,'Salmos 16:8','o SENHOR continuamente diante de mim'),
('solidão','Salmos',31,7,NULL,'Salmos 31:7','conheceste a minha alma nas angústias'),
('solidão','Salmos',42,8,NULL,'Salmos 42:8','de noite, o seu cântico está comigo'),
('solidão','Salmos',46,7,NULL,'Salmos 46:7','o SENHOR dos exércitos está conosco'),
('solidão','Salmos',73,23,24,'Salmos 73:23-24','seguraste a minha mão direita'),
('solidão','Salmos',94,14,NULL,'Salmos 94:14','o SENHOR não desamparará o seu povo'),
('solidão','Salmos',121,5,NULL,'Salmos 121:5','o SENHOR é quem te guarda'),
('solidão','Salmos',142,4,5,'Salmos 142:4-5','ninguém me reconhece; tu és o meu refúgio'),
('solidão','Salmos',145,18,NULL,'Salmos 145:18','perto está de todos os que o invocam'),
('solidão','Isaías',40,11,NULL,'Isaías 40:11','carrega os cordeirinhos no colo'),
('solidão','Isaías',49,15,16,'Isaías 49:15-16','nas palmas das minhas mãos te gravei'),
('solidão','Isaías',62,4,NULL,'Isaías 62:4','nunca mais te chamarão abandonada'),
('solidão','Mateus',18,20,NULL,'Mateus 18:20','onde dois ou três, ali estou'),
('solidão','Marcos',6,31,NULL,'Marcos 6:31','vinde à parte e descansai um pouco'),
('solidão','João',14,16,18,'João 14:16-18','não vos deixarei órfãos'),
('solidão','João',16,32,NULL,'João 16:32','não estou só: o Pai está comigo'),
('solidão','Atos',18,9,10,'Atos 18:9-10','não temas: eu estou contigo nesta cidade'),
('solidão','2 Timóteo',4,16,17,'2 Timóteo 4:16-17','todos me desampararam, mas o Senhor esteve comigo'),
('solidão','Hebreus',4,15,16,'Hebreus 4:15-16','um sacerdote que se compadece'),
('solidão','Salmos',133,1,NULL,'Salmos 133:1','quão bom viverem unidos os irmãos'),
('solidão','Apocalipse',3,20,NULL,'Apocalipse 3:20','estou à porta e bato; cearei com ele'),
-- LUTO -----------------------------------------------------------------------
('luto','Jó',1,21,NULL,'Jó 1:21','o SENHOR deu, o SENHOR tomou — a fé nua de Jó'),
('luto','2 Samuel',12,23,NULL,'2 Samuel 12:23','eu irei a ele; Davi e o filho'),
('luto','Salmos',6,8,9,'Salmos 6:8-9','o SENHOR ouviu a voz do meu pranto'),
('luto','Salmos',31,9,NULL,'Salmos 31:9','olhos consumidos de tristeza'),
('luto','Salmos',42,3,NULL,'Salmos 42:3','minhas lágrimas têm sido o meu alimento'),
('luto','Salmos',56,8,NULL,'Salmos 56:8','minhas lágrimas no teu odre e no teu livro'),
('luto','Salmos',77,1,2,'Salmos 77:1-2','a alma que recusa consolo e ainda clama'),
('luto','Salmos',88,1,2,'Salmos 88:1-2','clamo de dia e de noite — lamento sem verniz'),
('luto','Salmos',119,28,NULL,'Salmos 119:28','minha alma se derrete de tristeza; fortalece-me'),
('luto','Isaías',25,8,NULL,'Isaías 25:8','tragará a morte; enxugará as lágrimas de todos'),
('luto','Isaías',53,3,4,'Isaías 53:3-4','homem de dores: ele carregou as nossas'),
('luto','Isaías',57,15,NULL,'Isaías 57:15','habito com o contrito e abatido'),
('luto','Isaías',66,13,NULL,'Isaías 66:13','como a mãe consola, eu vos consolarei'),
('luto','Lamentações',3,31,32,'Lamentações 3:31-32','o Senhor não rejeita para sempre'),
('luto','João',11,35,NULL,'João 11:35','Jesus chorou'),
('luto','João',16,20,NULL,'João 16:20','a tristeza se converterá em alegria'),
('luto','Romanos',8,18,NULL,'Romanos 8:18','os sofrimentos e a glória a ser revelada'),
('luto','Romanos',12,15,NULL,'Romanos 12:15','chorai com os que choram'),
('luto','1 Coríntios',15,54,55,'1 Coríntios 15:54-55','onde está, ó morte, a tua vitória?'),
('luto','Filipenses',3,20,21,'Filipenses 3:20-21','nossa cidadania está nos céus'),
('luto','2 Coríntios',5,1,NULL,'2 Coríntios 5:1','temos um edifício de Deus, casa eterna'),
('luto','Hebreus',2,14,15,'Hebreus 2:14-15','liberta os que temiam a morte'),
('luto','1 Pedro',1,6,7,'1 Pedro 1:6-7','a tristeza de agora e a fé provada'),
('luto','Apocalipse',7,17,NULL,'Apocalipse 7:17','o Cordeiro os guiará às fontes'),
('luto','Apocalipse',14,13,NULL,'Apocalipse 14:13','descansarão das suas fadigas'),
('luto','Salmos',73,26,NULL,'Salmos 73:26','a carne desfalece; Deus é a rocha do coração'),
-- CULPA ----------------------------------------------------------------------
('culpa','Gênesis',3,9,NULL,'Gênesis 3:9','onde estás? — Deus procura quem se esconde'),
('culpa','2 Samuel',12,13,NULL,'2 Samuel 12:13','pequei — e o perdão imediato a Davi'),
('culpa','Salmos',32,1,2,'Salmos 32:1-2','feliz aquele cuja transgressão é perdoada'),
('culpa','Salmos',34,22,NULL,'Salmos 34:22','nenhum dos que nele confiam será condenado'),
('culpa','Salmos',51,1,2,'Salmos 51:1-2','apaga as minhas transgressões'),
('culpa','Salmos',51,17,NULL,'Salmos 51:17','o coração quebrantado Deus não despreza'),
('culpa','Salmos',86,5,NULL,'Salmos 86:5','tu és bom e pronto a perdoar'),
('culpa','Salmos',103,8,10,'Salmos 103:8-10','não nos trata segundo os nossos pecados'),
('culpa','Salmos',130,3,4,'Salmos 130:3-4','contigo está o perdão'),
('culpa','Provérbios',28,13,NULL,'Provérbios 28:13','quem confessa e deixa alcança misericórdia'),
('culpa','Isaías',44,22,NULL,'Isaías 44:22','desfaço as tuas transgressões como névoa'),
('culpa','Isaías',55,7,NULL,'Isaías 55:7','ele é generoso em perdoar'),
('culpa','Joel',2,13,NULL,'Joel 2:13','rasgai o coração, não as vestes'),
('culpa','Zacarias',3,4,NULL,'Zacarias 3:4','tirei a tua iniquidade; vestes novas'),
('culpa','Lucas',7,47,NULL,'Lucas 7:47','perdoada, amou muito'),
('culpa','Lucas',18,13,14,'Lucas 18:13-14','o publicano: tem misericórdia de mim'),
('culpa','Lucas',19,10,NULL,'Lucas 19:10','veio buscar e salvar o perdido'),
('culpa','Lucas',23,34,NULL,'Lucas 23:34','Pai, perdoa-lhes'),
('culpa','Lucas',23,42,43,'Lucas 23:42-43','hoje estarás comigo no paraíso'),
('culpa','João',3,17,NULL,'João 3:17','não veio para condenar o mundo'),
('culpa','João',8,10,11,'João 8:10-11','nem eu te condeno; vai e não peques mais'),
('culpa','Atos',3,19,NULL,'Atos 3:19','pecados apagados; tempos de refrigério'),
('culpa','Romanos',5,8,NULL,'Romanos 5:8','sendo nós ainda pecadores, Cristo morreu'),
('culpa','Romanos',5,20,NULL,'Romanos 5:20','onde abundou o pecado, superabundou a graça'),
('culpa','1 Timóteo',1,15,16,'1 Timóteo 1:15-16','veio salvar pecadores, dos quais eu sou o principal'),
('culpa','Salmos',65,3,NULL,'Salmos 65:3','nossas transgressões, tu as perdoas')
ON CONFLICT DO NOTHING;
